trailingComma: 'all'
tabWidth: 2
semi: false
singleQuote: true
printWidth: 120
arrowParens: 'avoid'
endOfLine: auto
bottomUnsortableImports:
    ['.(le|c|sc|sa)ss$', '.(gif|jpe?g|png|svg|webp|mp4|webm|wav|mp3|m4a)']
